### PR TITLE
all: remove existing translations

### PR DESCRIPTION
**Pull request by unknwon**

### CODE REVIEW

**Review by wuhan005 — APPROVED** [review]

**Comment by wuyunhua1987** [comment]
为什么要移除translations呢？文档里也没提到怎么做translations

**Comment by unknwon** [comment]
@wuyunhua1987 Good catch, I think the work to formalize the support of i18n in validator was overlooked. Please subscribe https://github.com/flamego/flamego/issues/128 for updates.

**Comment by wuyunhua1987** [comment]
> @wuyunhua1987 Good catch, I think the work to formalize the support of i18n in validator was overlooked. Please subscribe [flamego/flamego#128](https://github.com/flamego/flamego/issues/128) for updates.

thank you!

**Pull request merged**
